language: node_js
node_js:
  - "10"
dist: xenial
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - npm install -g chrome-webstore-upload-cli
script:
  - ng build --prod --base-href ./
  - webstore upload --source extension.zip --extension-id $EXTENSION_ID --client-id $CLIENT_ID --client-secret $CLIENT_SECRET --refresh-token $REFRESH_TOKEN